### ISSUE TITLE
tuya app/smart-life app

### ISSUE THREAD

**Issue by rafsch140365** [slametps/MMM-TuyaSL#4]
you can also make a version with the tuya app instead of the smart-life app. since i installed the tuya app i don't get any more data, but with the smart-life app
thanks

**Comment by slametps** [comment]
I don't know the application ID (see option **`bizType`**) for the Tuya app.

**Comment by slametps** [comment]
Pls try, set bizType to **`tuya`** in your config.

**Comment by rafsch140365** [comment]
ok thx it works with bizType to tuya

**Comment by slametps** [comment]
glad to hear. I'll close this thread.
